apiVersion: v2
name: cluster-api-ipam-provider-in-cluster
version: 0.1.4-dev
appVersion: "v0.0.1"
description: A Helm chart for cluster-api-ipam-provider-in-cluster
home: https://github.com/giantswarm/cluster-api-ipam-provider-in-cluster-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
sources:
  - https://github.com/giantswarm/cluster-api-ipam-provider-in-cluster-app
annotations:
  application.giantswarm.io/team: "rocket"
  io.giantswarm.application.team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
